// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKmUaBiZvMqbIB6RdjhP9WuIAecwyEiA',
    appId: '1:930750498644:web:1889855f8b9ef00e886ac1',
    messagingSenderId: '930750498644',
    projectId: 'hyemin-app',
    authDomain: 'hyemin-app.firebaseapp.com',
    storageBucket: 'hyemin-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wRJQBxlFK2Fz4ccZRcbuWDhZgAKTL9I',
    appId: '1:930750498644:android:9790fe885139197d886ac1',
    messagingSenderId: '930750498644',
    projectId: 'hyemin-app',
    storageBucket: 'hyemin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYvmhQuuq90rwKUqEFxv_f13gHWR7GRRY',
    appId: '1:930750498644:ios:e66c0df034cbbc51886ac1',
    messagingSenderId: '930750498644',
    projectId: 'hyemin-app',
    storageBucket: 'hyemin-app.firebasestorage.app',
    iosBundleId: 'com.example.hyemin2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYvmhQuuq90rwKUqEFxv_f13gHWR7GRRY',
    appId: '1:930750498644:ios:e66c0df034cbbc51886ac1',
    messagingSenderId: '930750498644',
    projectId: 'hyemin-app',
    storageBucket: 'hyemin-app.firebasestorage.app',
    iosBundleId: 'com.example.hyemin2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpKmUaBiZvMqbIB6RdjhP9WuIAecwyEiA',
    appId: '1:930750498644:web:ff66a94452573889886ac1',
    messagingSenderId: '930750498644',
    projectId: 'hyemin-app',
    authDomain: 'hyemin-app.firebaseapp.com',
    storageBucket: 'hyemin-app.firebasestorage.app',
  );
}
